// 6S LiPo Battery Configuration
// Generated by Config Wizard

CFG.batteries.push({
  id:      "6s",
  name:    "6S",
  cells:   6,
  voltage: 22.2,
  options: [
    { mah: 7000, weight: 850 },
    { mah: 8000, weight: 1100 },
    { mah: 10000, weight: 1300 },
    { mah: 12000, weight: 1600 }
  ]
});
