// Flightory Stallion V2 — Tricopter tilt-rotor VTOL
// Generated by Config Wizard

CFG.airframes.push({
  id:          "stallion-v2",
  name:        "Flightory Stallion V2",
  type:        "vtol",
  description: "Tricopter tilt-rotor VTOL",

  // Wing geometry
  wingArea:    0.2650,       // m²
  wingAreaDm2: 26.5,        // dm²
  wingspan:    1.340,       // m
  aspectRatio: 6.8,
  oswaldEff:   0.75,
  mac:         0.211,       // m

  // Fuselage bounding-box (for Gazebo inertia calc, solid-box approx)
  fuselageLength: 0.900,     // m  (X, forward)
  fuselageHeight: 0.160,     // m  (Z, vertical)

  // Center of gravity (link origin assumed at nose tip, Y=0 by symmetry)
  cogX:            0.430,    // m  (from nose along X; ~25% MAC typical)
  cogZ:            0.000,    // m  (+ = above mid-height, - = below)

  // Airfoil
  airfoilName: "Eppler E205",
  airfoilPolar: [
    [-4, -0.15, 0.012],
    [-2, 0.1, 0.009],
    [-0.5, 0.28, 0.008],
    [0, 0.35, 0.0075],
    [1, 0.5, 0.0072],
    [2, 0.65, 0.0074],
    [3, 0.78, 0.008],
    [4, 0.9, 0.009],
    [5, 1.02, 0.0105],
    [6, 1.12, 0.0125],
    [7, 1.2, 0.0155],
    [8, 1.25, 0.02],
    [9, 1.28, 0.026],
    [10, 1.28, 0.034],
    [11, 1.25, 0.044],
    [12, 1.18, 0.058]
  ],
  cd0Penalty:  0.008,
  clMax:       1.2,

  // Motor configuration
  numMotors:       3,
  numCruiseMotors: 2,
  motorLayout:     "tricopter-tilt",

  // Design limits
  auwMax:            3000,
  defaultFrameWeight: 1400,

  // Wing loading thresholds (g/dm²)
  wlCaution: 100,
  wlDanger:  115,

  // T/W thresholds
  twMin:  1.2,
  twGood: 1.5,

  // Power model
  transitionMult: 1.2,
  usableBattery:  0.80,

  // Compatibility filters (empty = all allowed)
  compatMotors:    [],
  compatProps:     [],
  compatBatteries: []
});
